#!/usr/bin/env bash
# setup.sh — Fast recovery script for bpf-verify after a sandbox reset.
#
# This script restores all runtime dependencies that are NOT stored in the
# GitHub repo (kernel source, clang, veristat) so the pipeline can run.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
#
# What it does:
#   1. Installs LLVM 23 nightly (clang-23) from apt.llvm.org
#   2. Fetches the bpf-next kernel source tarball from Google Drive
#   3. Extracts it to ~/bpf-next-0aa637869
#   4. Creates the generated kernel headers (autoconf.h, bounds.h, etc.)
#   5. Verifies the setup is complete
#
# After running this script, you can run:
#   python3 pipeline.py --compile-only   # test compilation
#   python3 pipeline.py                  # full pipeline with veristat

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KSRC="${HOME}/bpf-next-0aa637869"
KERNEL_COMMIT="0aa637869"
GDRIVE_FILE_ID="14spgX-TYzW9hTmhe6EPHg3VByHoZtN8M"   # Set this after first upload to Google Drive
GDRIVE_TARBALL="bpf-next-${KERNEL_COMMIT}.tar.gz"

info()  { echo "[INFO]  $*"; }
step()  { echo ""; echo "==> $*"; }
error() { echo "[ERROR] $*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Step 1: Install LLVM 23 nightly from apt.llvm.org
# ---------------------------------------------------------------------------
step "1/4  Installing LLVM 23 nightly (clang-23)"

if command -v clang-23 &>/dev/null; then
    info "clang-23 already installed: $(clang-23 --version | head -1)"
else
    info "Adding apt.llvm.org repository..."
    sudo apt-get install -y wget lsb-release software-properties-common gnupg 2>&1 | tail -3

    # Add GPG key
    wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
        | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc > /dev/null

    # Add LLVM 23 nightly repo (llvm-toolchain-jammy main = snapshot = LLVM 23)
    echo "deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy main" \
        | sudo tee /etc/apt/sources.list.d/llvm-23.list > /dev/null

    sudo apt-get update -qq 2>&1 | tail -3
    sudo apt-get install -y clang-23 llvm-23 lld-23 2>&1 | tail -5

    info "Installed: $(clang-23 --version | head -1)"
fi

# ---------------------------------------------------------------------------
# Step 2: Fetch bpf-next kernel source from Google Drive
# ---------------------------------------------------------------------------
step "2/4  Fetching bpf-next kernel source (commit ${KERNEL_COMMIT})"

if [ -d "${KSRC}/include/linux" ]; then
    info "Kernel source already present at ${KSRC}"
else
    if [ -n "${GDRIVE_FILE_ID}" ]; then
        info "Downloading ${GDRIVE_TARBALL} from Google Drive..."
        # Use rclone to download from Google Drive
        rclone copy "manus_google_drive:bpf-verify/${GDRIVE_TARBALL}" "${HOME}/" \
            --config "${HOME}/.gdrive-rclone.ini" \
            --progress 2>&1 | tail -5

        info "Extracting kernel source..."
        tar -xzf "${HOME}/${GDRIVE_TARBALL}" -C "${HOME}/"
        rm -f "${HOME}/${GDRIVE_TARBALL}"
        info "Kernel source extracted to ${KSRC}"
    else
        # Fallback: clone from kernel.org (slower but always works)
        info "No Google Drive file ID set. Cloning from kernel.org (this takes ~5 min)..."
        git clone --depth=1 \
            https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git \
            "${KSRC}" 2>&1 | tail -3
        info "Cloned bpf-next: $(git -C "${KSRC}" rev-parse --short HEAD)"
    fi
fi

# ---------------------------------------------------------------------------
# Step 3: Create generated kernel headers
# ---------------------------------------------------------------------------
step "3/4  Creating generated kernel headers"

GENERATED="${KSRC}/include/generated"
mkdir -p "${GENERATED}"

# autoconf.h — generated from /proc/config.gz (running kernel config)
if [ ! -f "${GENERATED}/autoconf.h" ]; then
    info "Generating autoconf.h from /proc/config.gz..."
    python3 - <<'PYEOF'
import gzip, os, re

ksrc = os.path.expanduser("~/bpf-next-0aa637869")
out_path = f"{ksrc}/include/generated/autoconf.h"

with gzip.open("/proc/config.gz", "rt") as f:
    lines = f.readlines()

with open(out_path, "w") as out:
    out.write("/* Automatically generated by setup.sh from /proc/config.gz */\n")
    out.write("#ifndef __GENERATED_AUTOCONF_H\n")
    out.write("#define __GENERATED_AUTOCONF_H\n\n")
    for line in lines:
        line = line.strip()
        if line.startswith("CONFIG_") and "=" in line:
            key, val = line.split("=", 1)
            if val == "y":
                out.write(f"#define {key} 1\n")
            elif val == "m":
                out.write(f"#define {key}_MODULE 1\n")
            elif val.startswith('"'):
                out.write(f"#define {key} {val}\n")
            else:
                out.write(f"#define {key} {val}\n")
        elif line.startswith("# CONFIG_") and "is not set" in line:
            key = line.split()[1]
            out.write(f"/* {key} is not set */\n")
    out.write("\n/* BPF compilation overrides */\n")
    out.write("#define CONFIG_PAGE_SHIFT 12\n")
    out.write("\n#endif /* __GENERATED_AUTOCONF_H */\n")

print(f"Generated {out_path} ({sum(1 for _ in open(out_path))} lines)")
PYEOF
fi

# bounds.h — empty stub (no CONFIG_NUMA zone bounds needed for BPF)
if [ ! -f "${GENERATED}/bounds.h" ]; then
    info "Creating bounds.h stub..."
    cat > "${GENERATED}/bounds.h" << 'EOF'
/* Automatically generated by setup.sh */
#ifndef __GENERATED_BOUNDS_H
#define __GENERATED_BOUNDS_H
#define NR_PAGEFLAGS 26
#define MAX_NR_ZONES 4
#define NR_MEM_TYPES 3
#endif
EOF
fi

# rq-offsets.h — empty stub (scheduler run-queue offsets, not needed for BPF)
if [ ! -f "${GENERATED}/rq-offsets.h" ]; then
    info "Creating rq-offsets.h stub..."
    cat > "${GENERATED}/rq-offsets.h" << 'EOF'
/* Automatically generated by setup.sh */
#ifndef __GENERATED_RQ_OFFSETS_H
#define __GENERATED_RQ_OFFSETS_H
#endif
EOF
fi

# timeconst.h — HZ-derived constants
if [ ! -f "${GENERATED}/timeconst.h" ]; then
    info "Creating timeconst.h stub..."
    cat > "${GENERATED}/timeconst.h" << 'EOF'
/* Automatically generated by setup.sh */
#ifndef __GENERATED_TIMECONST_H
#define __GENERATED_TIMECONST_H
#define HZ 250
#define NSEC_PER_JIFFIE 4000000UL
#define USEC_PER_JIFFIE 4000UL
#define MSEC_PER_JIFFIE 4UL
#endif
EOF
fi

# arch/x86/include/generated/uapi/asm/types.h — wraps asm-generic/types.h
X86_GENERATED="${KSRC}/arch/x86/include/generated"
mkdir -p "${X86_GENERATED}/uapi/asm" "${X86_GENERATED}/asm"

if [ ! -f "${X86_GENERATED}/uapi/asm/types.h" ]; then
    info "Creating x86 generated uapi/asm/types.h..."
    echo '#include <asm-generic/types.h>' > "${X86_GENERATED}/uapi/asm/types.h"
fi

if [ ! -f "${X86_GENERATED}/asm/rwonce.h" ]; then
    info "Creating x86 generated asm/rwonce.h..."
    echo '#include <asm-generic/rwonce.h>' > "${X86_GENERATED}/asm/rwonce.h"
fi

if [ ! -f "${X86_GENERATED}/asm/errno.h" ]; then
    info "Creating x86 generated asm/errno.h..."
    echo '#include <asm-generic/errno.h>' > "${X86_GENERATED}/asm/errno.h"
fi

if [ ! -f "${KSRC}/include/linux/compiler-version.h" ]; then
    info "Creating compiler-version.h stub..."
    cat > "${KSRC}/include/linux/compiler-version.h" << 'EOF'
/* Automatically generated by setup.sh */
#ifndef __LINUX_COMPILER_VERSION_H
#define __LINUX_COMPILER_VERSION_H
/* Clang 23 nightly */
#define CONFIG_CC_VERSION_TEXT "clang version 23.0.0"
#define CONFIG_CLANG_VERSION 230000
#endif
EOF
fi

# asm-offsets.h — empty stub
if [ ! -f "${KSRC}/include/generated/asm-offsets.h" ]; then
    info "Creating asm-offsets.h stub..."
    printf '/* empty */\n' > "${KSRC}/include/generated/asm-offsets.h"
fi

info "Generated headers created."

# ---------------------------------------------------------------------------
# Step 4: Verify setup
# ---------------------------------------------------------------------------
step "4/4  Verifying setup"

CLANG="/usr/bin/clang-23"
LLVM_OBJCOPY="/usr/bin/llvm-objcopy-23"

# Quick compile test
TEST_OUT=$(${CLANG} -target bpf -O2 -nostdinc \
    -I"${KSRC}/include" \
    -I"${KSRC}/include/uapi" \
    -I"${KSRC}/include/generated/uapi" \
    -I"${KSRC}/arch/x86/include" \
    -I"${KSRC}/arch/x86/include/uapi" \
    -I"${KSRC}/arch/x86/include/generated" \
    -I"${KSRC}/arch/x86/include/generated/uapi" \
    -I"${SCRIPT_DIR}/shims" \
    -I"${SCRIPT_DIR}/shims/uapi" \
    -I"${SCRIPT_DIR}/shims/asm" \
    -I"${SCRIPT_DIR}/shims/linux" \
    -include "${KSRC}/include/linux/kconfig.h" \
    -D__KERNEL__ -DBPF_NO_PRESERVE_ACCESS_INDEX \
    -x c -c /dev/null -o /dev/null 2>&1 || true)

if [ -z "${TEST_OUT}" ]; then
    info "Compile test: PASSED"
else
    info "Compile test output: ${TEST_OUT}"
fi

echo ""
info "Setup complete!"
info ""
info "  clang-23:       $(clang-23 --version | head -1)"
info "  llvm-objcopy:   $(llvm-objcopy-23 --version | head -1)"
info "  Kernel source:  ${KSRC}"
info "  Commit:         $(git -C "${KSRC}" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
info ""
info "Run the pipeline:"
info "  cd ${SCRIPT_DIR}"
info "  python3 pipeline.py --compile-only"
info "  python3 pipeline.py"
