/* BPF verification harness for disasm
 * Auto-generated by bpf-verify pipeline
 */

/* ---------------------------------------------------------------
 * Step 0: Override autoconf.h CONFIG_* settings that cause BPF
 * compilation failures. kconfig.h (force-included via -include)
 * pulls in generated/autoconf.h which may define these as 1.
 * We undef them here so they take effect before kernel headers.
 * --------------------------------------------------------------- */
/* CONFIG_NUMA pulls in asm/sparsemem.h and NUMA-specific types */
#undef CONFIG_NUMA
/* CONFIG_PARAVIRT pulls in x86 inline asm in paravirt.h */
#undef CONFIG_PARAVIRT
/* CONFIG_MEMCG pulls in this_cpu_read/write (x86 percpu inline asm) in sched/mm.h */
#undef CONFIG_MEMCG

/* ---------------------------------------------------------------
 * Step 1: Suppress kernel export / module metadata macros.
 * These produce non-BPF ELF sections that libbpf cannot handle.
 * --------------------------------------------------------------- */
#define EXPORT_SYMBOL(x)
#define EXPORT_SYMBOL_GPL(x)
#define EXPORT_SYMBOL_NS(x, ns)
#define EXPORT_SYMBOL_NS_GPL(x, ns)
#define MODULE_LICENSE(x)
#define MODULE_AUTHOR(x)
#define MODULE_DESCRIPTION(x)
#define EXPORT_TRACEPOINT_SYMBOL(x)
#define EXPORT_TRACEPOINT_SYMBOL_GPL(x)
#define module_init(x)
#define module_exit(x)

/* ---------------------------------------------------------------
 * Step 1: Suppress WARN_ON / BUG_ON / printk family.
 *
 * These macros call warn_slowpath_fmt, printk, etc. -- functions
 * that are not available in the BPF execution environment and
 * produce unresolved extern symbols that block libbpf loading.
 *
 * For static analysis purposes we want to verify the data-path
 * logic, not the diagnostic/logging paths, so suppressing them
 * is semantically correct for this use case.
 *
 * WARN_ON / WARN must return a scalar (int) because they are
 * commonly used inside if() conditions in kernel code.
 * --------------------------------------------------------------- */
#define WARN_ON(cond)              (0)
#define WARN_ON_ONCE(cond)         (0)
#define WARN(cond, fmt, ...)       (0)
#define WARN_ONCE(cond, fmt, ...)  (0)
#define BUG()                      do {} while (0)
#define BUG_ON(cond)               do { if (cond) {} } while (0)

/* printk / pr_* family -- produce string-literal .rodata relocations */
#define printk(fmt, ...)           do {} while (0)
#define pr_emerg(fmt, ...)         do {} while (0)
#define pr_alert(fmt, ...)         do {} while (0)
#define pr_crit(fmt, ...)          do {} while (0)
#define pr_err(fmt, ...)           do {} while (0)
#define pr_warn(fmt, ...)          do {} while (0)
#define pr_notice(fmt, ...)        do {} while (0)
#define pr_info(fmt, ...)          do {} while (0)
#define pr_debug(fmt, ...)         do {} while (0)
#define pr_devel(fmt, ...)         do {} while (0)
#define pr_cont(fmt, ...)          do {} while (0)

/* ---------------------------------------------------------------
 * Step 1b: Suppress _printk, panic, jiffies.
 *
 * _printk is the actual symbol printk resolves to at link time.
 * panic() calls into the kernel crash path - not available in BPF.
 * jiffies is a per-CPU variable exported from the kernel - not
 * accessible in BPF context without a helper.
 *
 * We define jiffies as a compile-time constant (0) so arithmetic
 * on it is valid; panic as an infinite loop (unreachable in
 * practice); _printk as a no-op.
 * --------------------------------------------------------------- */
/* linux/printk.h, linux/panic.h, and linux/module.h are blocked via
 * -D flags in BPF_CFLAGS so their include guards are pre-defined.
 * We define the symbols those headers would have provided here. */
#define _printk(fmt, ...)          do {} while (0)
#define vprintk(fmt, args)         do {} while (0)
#define printk_deferred(fmt, ...)  do {} while (0)
#define panic(fmt, ...)            do {} while (0)
/* Also stub out common printk-related types/macros that other headers use */
#define printk_ratelimit()         0
#define printk_timed_ratelimit(a,b) 0
/* jiffies: linux/jiffies.h declares it as 'extern unsigned long volatile jiffies'.
 * We cannot block that header (it pulls in linux/types.h etc.).
 * Instead we undef the extern declaration after the include and redefine
 * jiffies as a compile-time constant. This is done in the post-include
 * section below, after all kernel headers have been processed. */

/* BPF_ASSERT: property assertion for verification.
 * If the condition is false the program returns -1 (XDP_ABORTED / TC_ACT_SHOT),
 * which veristat reports as a non-zero return value.
 * Using return -1 instead of a null pointer write avoids the BPF verifier
 * rejecting programs where the false branch is provably unreachable but the
 * verifier still explores it (e.g., pointer equality comparisons). */
#define BPF_ASSERT(cond) do { if (!(cond)) { return -1; } } while(0)

/* BPF map for dynamic (non-constant) inputs.
 * IMPORTANT: This MUST be defined BEFORE the kernel source include.
 * The LLVM BPF backend generates the BTF DATASEC for '.maps' when it
 * first sees the map struct. If kernel headers included later redefine
 * __uint/__type, the DATASEC is already correctly generated.
 *
 * We use the BTF-based map definition syntax that clang understands
 * without needing bpf_helpers.h. The macros below replicate what
 * bpf_helpers.h provides but using only kernel-available types. */
/* Pull in linux/types.h first so __u32/__u64 are available for the
 * map struct definition below. This must come before the source include
 * so the map DATASEC is generated before kernel headers can redefine
 * __uint/__type. */
#include <linux/types.h>

/* Force-undefine __uint and __type before defining the map struct.
 * Kernel headers may define these differently; we need our exact form
 * for the LLVM BPF backend to generate a DATASEC entry in BTF. */
#undef __uint
#undef __type
#define __uint(name, val) int (*name)[val]
#define __type(name, val) typeof(val) *name
struct {
    __uint(type, 1 /* BPF_MAP_TYPE_ARRAY */);
    __uint(max_entries, 4);
    __type(key, __u32);
    __type(value, __u64);
} input_map __attribute__((section(".maps"), used));

/* bpf_map_lookup_elem helper declaration */
static void *(*bpf_map_lookup_elem)(void *map, const void *key) =
    (void *) 1 /* BPF_FUNC_map_lookup_elem */;

/* Extra dependencies (other translation units this file calls into) */

/* Per-file pre-include code: macros/stubs injected BEFORE the source file
 * (e.g. identity macros to suppress 6-arg non-static functions). */
/* Block linux/bpf.h: it pulls in linux/percpu.h, linux/mm_types.h, etc.
 * The shim provides struct bpf_insn and all BPF constants directly. */
#define _LINUX_BPF_H 1
/* Block linux/kernel.h to avoid the __printf(3,4) conflict with clang
 * system headers.  The shim provides its own disasm.h replacement. */
#define _LINUX_KERNEL_H
/* Stub verbose() as a no-op: print_bpf_insn() uses a variadic callback
 * (bpf_insn_print_t) with >5 arguments, which the BPF backend rejects.
 * We only verify func_id_name() and the string tables, not print_bpf_insn.
 * Stubbing verbose() allows the whole file to compile without errors. */
#define verbose(priv, fmt, ...) ((void)(priv))
/* Stub snprintf: disasm.c uses it only to format fallback strings into
 * a caller-supplied buffer (buff).  Returning 0 is safe -- the caller
 * always returns buff regardless of the return value. */
#define snprintf(buf, size, fmt, ...) (0)
/* Stub strcpy: used once in print_bpf_insn for the "unknown" fallback. */
static __always_inline char *__bpf_strcpy(char *d, const char *s)
{
    char *r = d;
    while ((*d++ = *s++));
    return r;
}
#define strcpy(d, s) __bpf_strcpy(d, s)
/* Provide __stringify since linux/stringify.h is blocked by _LINUX_KERNEL_H. */
#ifndef __stringify
#define __stringify(x) #x
#endif
/* Provide BUILD_BUG_ON as a no-op (used in __func_get_name). */
#ifndef BUILD_BUG_ON
#define BUILD_BUG_ON(cond) ((void)(cond))
#endif

/* Include the kernel source file */
#include "/home/ubuntu/bpf-verify/shims/disasm/disasm-shim.c"

/* Per-file extra preamble: stubs injected AFTER the source file include
 * (so they can reference types defined in the source). */
static void disasm_count_cb(void *private_data, const char *fmt, ...)
{
    int *cnt = (int *)private_data;
    (*cnt)++;
}


/* Post-include fixups: redefine symbols that were declared as externs
 * in kernel headers but must be constants in the BPF context.
 * We undef the extern variable and redefine as a compile-time constant
 * so that any code using jiffies gets a constant 0 instead of a
 * memory load from a kernel variable that does not exist in BPF. */
#ifdef jiffies
#undef jiffies
#endif
#define jiffies ((unsigned long)0)

/* Suppress compiler hint macros that generate extern BTF references.
 * 'unlikely' and 'likely' are normally __builtin_expect wrappers, but
 * some kernel headers define them as macros that call a function when
 * the compiler is in certain modes. Force them to plain expressions.
 * These are re-undef'd here in case the kernel source redefined them. */
#undef unlikely
#undef likely
#define unlikely(x) (x)
#define likely(x)   (x)

/* BPF program entry point - socket filter type (minimal requirements) */
__attribute__((section("socket"), used))
int bpf_prog_disasm(void *ctx)
{
    /* disasm: BPF instruction disassembler.
     *
     * print_bpf_insn() is built around a variadic callback (bpf_insn_print_t)
     * which the BPF backend cannot support (variadic functions and >5-arg calls
     * are both rejected).  We therefore verify the non-variadic parts of
     * disasm.c:
     *
     *   func_id_name(id)   -- array lookup: returns the string name of a BPF
     *                         helper function ID, or "unknown" for invalid IDs.
     *   bpf_class_string[] -- string table for BPF instruction classes.
     *   bpf_alu_string[]   -- string table for ALU operations.
     *
     * Properties verified:
     *   1. func_id_name(known_id) != NULL  (no null entry for valid helpers)
     *   2. func_id_name(-1) != NULL        (out-of-range returns "unknown")
     *   3. func_id_name(0) != NULL         (BPF_FUNC_unspec is valid)
     *   4. bpf_class_string[BPF_LD >> 0] != NULL
     *   5. bpf_alu_string[BPF_ADD >> 4] != NULL
     */

    /* 1. Known helper ID returns non-NULL name */
    BPF_ASSERT(func_id_name(BPF_FUNC_map_lookup_elem) != 0);

    /* 2. Out-of-range ID returns "unknown" (non-NULL) */
    BPF_ASSERT(func_id_name(-1) != 0);

    /* 3. BPF_FUNC_unspec (id=0) returns non-NULL */
    BPF_ASSERT(func_id_name(0) != 0);

    /* 4. bpf_class_string table is populated for BPF_LD class */
    BPF_ASSERT(bpf_class_string[BPF_LD] != 0);

    /* 5. bpf_alu_string table is populated for BPF_ADD operation */
    BPF_ASSERT(bpf_alu_string[BPF_ADD >> 4] != 0);

    return 0;
    return 0;
}

__attribute__((section("license"), used))
char _license[] = "GPL";
