/* BPF verification harness for lpm_trie
 * Auto-generated by bpf-verify pipeline
 */

/* ---------------------------------------------------------------
 * Step 0: Override autoconf.h CONFIG_* settings that cause BPF
 * compilation failures. kconfig.h (force-included via -include)
 * pulls in generated/autoconf.h which may define these as 1.
 * We undef them here so they take effect before kernel headers.
 * --------------------------------------------------------------- */
/* CONFIG_NUMA pulls in asm/sparsemem.h and NUMA-specific types */
#undef CONFIG_NUMA
/* CONFIG_PARAVIRT pulls in x86 inline asm in paravirt.h */
#undef CONFIG_PARAVIRT
/* CONFIG_MEMCG pulls in this_cpu_read/write (x86 percpu inline asm) in sched/mm.h */
#undef CONFIG_MEMCG

/* ---------------------------------------------------------------
 * Step 1: Suppress kernel export / module metadata macros.
 * These produce non-BPF ELF sections that libbpf cannot handle.
 * --------------------------------------------------------------- */
#define EXPORT_SYMBOL(x)
#define EXPORT_SYMBOL_GPL(x)
#define EXPORT_SYMBOL_NS(x, ns)
#define EXPORT_SYMBOL_NS_GPL(x, ns)
#define MODULE_LICENSE(x)
#define MODULE_AUTHOR(x)
#define MODULE_DESCRIPTION(x)
#define EXPORT_TRACEPOINT_SYMBOL(x)
#define EXPORT_TRACEPOINT_SYMBOL_GPL(x)
#define module_init(x)
#define module_exit(x)

/* ---------------------------------------------------------------
 * Step 1: Suppress WARN_ON / BUG_ON / printk family.
 *
 * These macros call warn_slowpath_fmt, printk, etc. -- functions
 * that are not available in the BPF execution environment and
 * produce unresolved extern symbols that block libbpf loading.
 *
 * For static analysis purposes we want to verify the data-path
 * logic, not the diagnostic/logging paths, so suppressing them
 * is semantically correct for this use case.
 *
 * WARN_ON / WARN must return a scalar (int) because they are
 * commonly used inside if() conditions in kernel code.
 * --------------------------------------------------------------- */
#define WARN_ON(cond)              (0)
#define WARN_ON_ONCE(cond)         (0)
#define WARN(cond, fmt, ...)       (0)
#define WARN_ONCE(cond, fmt, ...)  (0)
#define BUG()                      do {} while (0)
#define BUG_ON(cond)               do { if (cond) {} } while (0)

/* printk / pr_* family -- produce string-literal .rodata relocations */
#define printk(fmt, ...)           do {} while (0)
#define pr_emerg(fmt, ...)         do {} while (0)
#define pr_alert(fmt, ...)         do {} while (0)
#define pr_crit(fmt, ...)          do {} while (0)
#define pr_err(fmt, ...)           do {} while (0)
#define pr_warn(fmt, ...)          do {} while (0)
#define pr_notice(fmt, ...)        do {} while (0)
#define pr_info(fmt, ...)          do {} while (0)
#define pr_debug(fmt, ...)         do {} while (0)
#define pr_devel(fmt, ...)         do {} while (0)
#define pr_cont(fmt, ...)          do {} while (0)

/* ---------------------------------------------------------------
 * Step 1b: Suppress _printk, panic, jiffies.
 *
 * _printk is the actual symbol printk resolves to at link time.
 * panic() calls into the kernel crash path - not available in BPF.
 * jiffies is a per-CPU variable exported from the kernel - not
 * accessible in BPF context without a helper.
 *
 * We define jiffies as a compile-time constant (0) so arithmetic
 * on it is valid; panic as an infinite loop (unreachable in
 * practice); _printk as a no-op.
 * --------------------------------------------------------------- */
/* linux/printk.h, linux/panic.h, and linux/module.h are blocked via
 * -D flags in BPF_CFLAGS so their include guards are pre-defined.
 * We define the symbols those headers would have provided here. */
#define _printk(fmt, ...)          do {} while (0)
#define vprintk(fmt, args)         do {} while (0)
#define printk_deferred(fmt, ...)  do {} while (0)
#define panic(fmt, ...)            do {} while (0)
/* Also stub out common printk-related types/macros that other headers use */
#define printk_ratelimit()         0
#define printk_timed_ratelimit(a,b) 0
/* jiffies: linux/jiffies.h declares it as 'extern unsigned long volatile jiffies'.
 * We cannot block that header (it pulls in linux/types.h etc.).
 * Instead we undef the extern declaration after the include and redefine
 * jiffies as a compile-time constant. This is done in the post-include
 * section below, after all kernel headers have been processed. */

/* BPF_ASSERT: property assertion for verification.
 * If the condition is false the program returns -1 (XDP_ABORTED / TC_ACT_SHOT),
 * which veristat reports as a non-zero return value.
 * Using return -1 instead of a null pointer write avoids the BPF verifier
 * rejecting programs where the false branch is provably unreachable but the
 * verifier still explores it (e.g., pointer equality comparisons). */
#define BPF_ASSERT(cond) do { if (!(cond)) { return -1; } } while(0)

/* BPF map for dynamic (non-constant) inputs.
 * IMPORTANT: This MUST be defined BEFORE the kernel source include.
 * The LLVM BPF backend generates the BTF DATASEC for '.maps' when it
 * first sees the map struct. If kernel headers included later redefine
 * __uint/__type, the DATASEC is already correctly generated.
 *
 * We use the BTF-based map definition syntax that clang understands
 * without needing bpf_helpers.h. The macros below replicate what
 * bpf_helpers.h provides but using only kernel-available types. */
/* Pull in linux/types.h first so __u32/__u64 are available for the
 * map struct definition below. This must come before the source include
 * so the map DATASEC is generated before kernel headers can redefine
 * __uint/__type. */
#include <linux/types.h>

/* Force-undefine __uint and __type before defining the map struct.
 * Kernel headers may define these differently; we need our exact form
 * for the LLVM BPF backend to generate a DATASEC entry in BTF. */
#undef __uint
#undef __type
#define __uint(name, val) int (*name)[val]
#define __type(name, val) typeof(val) *name
struct {
    __uint(type, 1 /* BPF_MAP_TYPE_ARRAY */);
    __uint(max_entries, 4);
    __type(key, __u32);
    __type(value, __u64);
} input_map __attribute__((section(".maps"), used));

/* bpf_map_lookup_elem helper declaration */
static void *(*bpf_map_lookup_elem)(void *map, const void *key) =
    (void *) 1 /* BPF_FUNC_map_lookup_elem */;

/* Extra dependencies (other translation units this file calls into) */

/* Per-file pre-include code: macros/stubs injected BEFORE the source file
 * (e.g. identity macros to suppress 6-arg non-static functions). */

/* Include the kernel source file */
#include "/home/ubuntu/bpf-verify/shims/lpm_trie/lpm_trie-shim.c"

/* Per-file extra preamble: stubs injected AFTER the source file include
 * (so they can reference types defined in the source). */


/* Post-include fixups: redefine symbols that were declared as externs
 * in kernel headers but must be constants in the BPF context.
 * We undef the extern variable and redefine as a compile-time constant
 * so that any code using jiffies gets a constant 0 instead of a
 * memory load from a kernel variable that does not exist in BPF. */
#ifdef jiffies
#undef jiffies
#endif
#define jiffies ((unsigned long)0)

/* Suppress compiler hint macros that generate extern BTF references.
 * 'unlikely' and 'likely' are normally __builtin_expect wrappers, but
 * some kernel headers define them as macros that call a function when
 * the compiler is in certain modes. Force them to plain expressions.
 * These are re-undef'd here in case the kernel source redefined them. */
#undef unlikely
#undef likely
#define unlikely(x) (x)
#define likely(x)   (x)

/* BPF program entry point - socket filter type (minimal requirements) */
__attribute__((section("socket"), used))
int bpf_prog_lpm_trie(void *ctx)
{
    /* lpm_trie: BPF Longest-Prefix-Match trie core algorithm.
     *
     * The BPF verifier cannot track pointers stored in and retrieved from
     * memory structures (pointer aliasing through memory). This means we
     * cannot call trie_update_elem() + trie_lookup_elem() end-to-end, because
     * after trie->root = new_node (a memory store), the verifier loses track
     * of the pointer and rejects the subsequent dereference as 'scalar'.
     *
     * Instead we test the two core pure algorithmic functions directly:
     *   1. extract_bit(data, index): extracts bit 'index' from a byte array.
     *   2. longest_prefix_match(trie, node, key): finds the longest common
     *      prefix between a trie node and a lookup key.
     *
     * Both functions operate only on stack-allocated data, which the verifier
     * can fully track. This exercises the heart of the LPM algorithm.
     *
     * Properties verified:
     *   A. extract_bit: bit 0 of 0x80 is 1; bit 7 of 0x01 is 1; bit 0 of 0x00 is 0.
     *   B. longest_prefix_match: 192.168.1.x node vs 192.168.1.5 key -> 24 bits match.
     *   C. longest_prefix_match: 10.0.0.0/8 node vs 192.168.1.5 key -> 0 bits match.
     *   D. longest_prefix_match: exact match 192.168.1.0/24 -> returns min(24,32)=24.
     */

    /* --- Property A: extract_bit --- */
    u8 data_a[4] = {0x80, 0x00, 0x00, 0x01}; /* 10000000 00000000 00000000 00000001 */
    BPF_ASSERT(extract_bit(data_a, 0) == 1);  /* MSB of 0x80 */
    BPF_ASSERT(extract_bit(data_a, 1) == 0);  /* bit 1 of 0x80 */
    BPF_ASSERT(extract_bit(data_a, 31) == 1); /* LSB of 0x01 */
    BPF_ASSERT(extract_bit(data_a, 8) == 0);  /* MSB of 0x00 */

    /* --- Properties B, C, D: longest_prefix_match --- */
    /* Build a minimal lpm_trie descriptor (data_size=4, max_prefixlen=32) */
    struct lpm_trie trie;
    lpm_trie_init(&trie, 8);

    /* Node: 192.168.1.0/24 */
    struct {
        struct lpm_trie_node hdr;
        u8 addr[4];
        u64 value;
    } node24;
    node24.hdr.prefixlen = 24;
    node24.hdr.flags = 0;
    node24.hdr.child[0] = NULL;
    node24.hdr.child[1] = NULL;
    node24.addr[0] = 192; node24.addr[1] = 168;
    node24.addr[2] = 1;   node24.addr[3] = 0;
    node24.value = 1;

    /* Key: 192.168.1.5/32 */
    struct lpm_key_ipv4 key32;
    lpm_key_set(&key32, 32, 192, 168, 1, 5);

    /* B: 192.168.1.0/24 node vs 192.168.1.5/32 key -> 24 bits match */
    size_t match_b = longest_prefix_match(&trie, &node24.hdr, &key32.hdr);
    BPF_ASSERT(match_b == 24);

    /* Node: 10.0.0.0/8 */
    struct {
        struct lpm_trie_node hdr;
        u8 addr[4];
        u64 value;
    } node8;
    node8.hdr.prefixlen = 8;
    node8.hdr.flags = 0;
    node8.hdr.child[0] = NULL;
    node8.hdr.child[1] = NULL;
    node8.addr[0] = 10;  node8.addr[1] = 0;
    node8.addr[2] = 0;   node8.addr[3] = 0;
    node8.value = 10;

    /* C: 10.0.0.0/8 node vs 192.168.1.5/32 key -> 0 bits match */
    size_t match_c = longest_prefix_match(&trie, &node8.hdr, &key32.hdr);
    BPF_ASSERT(match_c == 0);

    /* D: exact match -- 192.168.1.0/24 node vs 192.168.1.0/24 key -> 24 */
    struct lpm_key_ipv4 key24;
    lpm_key_set(&key24, 24, 192, 168, 1, 0);
    size_t match_d = longest_prefix_match(&trie, &node24.hdr, &key24.hdr);
    BPF_ASSERT(match_d == 24);

    return (int)(match_b + match_c + match_d);
    return 0;
}

__attribute__((section("license"), used))
char _license[] = "GPL";
