/* BPF verification harness for min_heap
 * Auto-generated by bpf-verify pipeline
 */

/* ---------------------------------------------------------------
 * Step 0: Override autoconf.h CONFIG_* settings that cause BPF
 * compilation failures. kconfig.h (force-included via -include)
 * pulls in generated/autoconf.h which may define these as 1.
 * We undef them here so they take effect before kernel headers.
 * --------------------------------------------------------------- */
/* CONFIG_NUMA pulls in asm/sparsemem.h and NUMA-specific types */
#undef CONFIG_NUMA
/* CONFIG_PARAVIRT pulls in x86 inline asm in paravirt.h */
#undef CONFIG_PARAVIRT
/* CONFIG_MEMCG pulls in this_cpu_read/write (x86 percpu inline asm) in sched/mm.h */
#undef CONFIG_MEMCG

/* ---------------------------------------------------------------
 * Step 1: Suppress kernel export / module metadata macros.
 * These produce non-BPF ELF sections that libbpf cannot handle.
 * --------------------------------------------------------------- */
#define EXPORT_SYMBOL(x)
#define EXPORT_SYMBOL_GPL(x)
#define EXPORT_SYMBOL_NS(x, ns)
#define EXPORT_SYMBOL_NS_GPL(x, ns)
#define MODULE_LICENSE(x)
#define MODULE_AUTHOR(x)
#define MODULE_DESCRIPTION(x)
#define EXPORT_TRACEPOINT_SYMBOL(x)
#define EXPORT_TRACEPOINT_SYMBOL_GPL(x)
#define module_init(x)
#define module_exit(x)

/* ---------------------------------------------------------------
 * Step 1: Suppress WARN_ON / BUG_ON / printk family.
 *
 * These macros call warn_slowpath_fmt, printk, etc. -- functions
 * that are not available in the BPF execution environment and
 * produce unresolved extern symbols that block libbpf loading.
 *
 * For static analysis purposes we want to verify the data-path
 * logic, not the diagnostic/logging paths, so suppressing them
 * is semantically correct for this use case.
 *
 * WARN_ON / WARN must return a scalar (int) because they are
 * commonly used inside if() conditions in kernel code.
 * --------------------------------------------------------------- */
#define WARN_ON(cond)              (0)
#define WARN_ON_ONCE(cond)         (0)
#define WARN(cond, fmt, ...)       (0)
#define WARN_ONCE(cond, fmt, ...)  (0)
#define BUG()                      do {} while (0)
#define BUG_ON(cond)               do { if (cond) {} } while (0)

/* printk / pr_* family -- produce string-literal .rodata relocations */
#define printk(fmt, ...)           do {} while (0)
#define pr_emerg(fmt, ...)         do {} while (0)
#define pr_alert(fmt, ...)         do {} while (0)
#define pr_crit(fmt, ...)          do {} while (0)
#define pr_err(fmt, ...)           do {} while (0)
#define pr_warn(fmt, ...)          do {} while (0)
#define pr_notice(fmt, ...)        do {} while (0)
#define pr_info(fmt, ...)          do {} while (0)
#define pr_debug(fmt, ...)         do {} while (0)
#define pr_devel(fmt, ...)         do {} while (0)
#define pr_cont(fmt, ...)          do {} while (0)

/* ---------------------------------------------------------------
 * Step 1b: Suppress _printk, panic, jiffies.
 *
 * _printk is the actual symbol printk resolves to at link time.
 * panic() calls into the kernel crash path - not available in BPF.
 * jiffies is a per-CPU variable exported from the kernel - not
 * accessible in BPF context without a helper.
 *
 * We define jiffies as a compile-time constant (0) so arithmetic
 * on it is valid; panic as an infinite loop (unreachable in
 * practice); _printk as a no-op.
 * --------------------------------------------------------------- */
/* linux/printk.h, linux/panic.h, and linux/module.h are blocked via
 * -D flags in BPF_CFLAGS so their include guards are pre-defined.
 * We define the symbols those headers would have provided here. */
#define _printk(fmt, ...)          do {} while (0)
#define vprintk(fmt, args)         do {} while (0)
#define printk_deferred(fmt, ...)  do {} while (0)
#define panic(fmt, ...)            do {} while (0)
/* Also stub out common printk-related types/macros that other headers use */
#define printk_ratelimit()         0
#define printk_timed_ratelimit(a,b) 0
/* jiffies: linux/jiffies.h declares it as 'extern unsigned long volatile jiffies'.
 * We cannot block that header (it pulls in linux/types.h etc.).
 * Instead we undef the extern declaration after the include and redefine
 * jiffies as a compile-time constant. This is done in the post-include
 * section below, after all kernel headers have been processed. */

/* BPF_ASSERT: property assertion for verification.
 * If the condition is false the program returns -1 (XDP_ABORTED / TC_ACT_SHOT),
 * which veristat reports as a non-zero return value.
 * Using return -1 instead of a null pointer write avoids the BPF verifier
 * rejecting programs where the false branch is provably unreachable but the
 * verifier still explores it (e.g., pointer equality comparisons). */
#define BPF_ASSERT(cond) do { if (!(cond)) { return -1; } } while(0)

/* BPF map for dynamic (non-constant) inputs.
 * IMPORTANT: This MUST be defined BEFORE the kernel source include.
 * The LLVM BPF backend generates the BTF DATASEC for '.maps' when it
 * first sees the map struct. If kernel headers included later redefine
 * __uint/__type, the DATASEC is already correctly generated.
 *
 * We use the BTF-based map definition syntax that clang understands
 * without needing bpf_helpers.h. The macros below replicate what
 * bpf_helpers.h provides but using only kernel-available types. */
/* Pull in linux/types.h first so __u32/__u64 are available for the
 * map struct definition below. This must come before the source include
 * so the map DATASEC is generated before kernel headers can redefine
 * __uint/__type. */
#include <linux/types.h>

/* Force-undefine __uint and __type before defining the map struct.
 * Kernel headers may define these differently; we need our exact form
 * for the LLVM BPF backend to generate a DATASEC entry in BTF. */
#undef __uint
#undef __type
#define __uint(name, val) int (*name)[val]
#define __type(name, val) typeof(val) *name
struct {
    __uint(type, 1 /* BPF_MAP_TYPE_ARRAY */);
    __uint(max_entries, 4);
    __type(key, __u32);
    __type(value, __u64);
} input_map __attribute__((section(".maps"), used));

/* bpf_map_lookup_elem helper declaration */
static void *(*bpf_map_lookup_elem)(void *map, const void *key) =
    (void *) 1 /* BPF_FUNC_map_lookup_elem */;

/* Extra dependencies (other translation units this file calls into) */

/* Per-file pre-include code: macros/stubs injected BEFORE the source file
 * (e.g. identity macros to suppress 6-arg non-static functions). */
/* Provide memcpy as static inline to avoid extern BTF resolution failure.
 * min_heap.c calls memcpy internally; libbpf needs BTF for all externs. */
static inline void *memcpy(void *dst, const void *src, __kernel_size_t n)
{
    unsigned char *d = (unsigned char *)dst;
    const unsigned char *s = (const unsigned char *)src;
    while (n--)
        *d++ = *s++;
    return dst;
}
/* File-scope callback functions for the int min-heap.
 * These are defined here (before the source include) so they are
 * available to the harness body which runs after the source include. */
static bool __bpf_int_less(const void *a, const void *b, void *args) {
    return *(const int *)a < *(const int *)b;
}
static void __bpf_int_swap(void *a, void *b, void *args) {
    int t = *(int *)a;
    *(int *)a = *(int *)b;
    *(int *)b = t;
}

/* Include the kernel source file */
#include "/home/ubuntu/bpf-next-0aa637869/lib/min_heap.c"

/* Per-file extra preamble: stubs injected AFTER the source file include
 * (so they can reference types defined in the source). */
/* Typed heap storage: 8 preallocated int slots.
 * Defined here (after min_heap.c is included) so MIN_HEAP_PREALLOCATED
 * is available from linux/min_heap.h. */
MIN_HEAP_PREALLOCATED(int, bpf_int_heap, 8) __bpf_heap_storage;


/* Post-include fixups: redefine symbols that were declared as externs
 * in kernel headers but must be constants in the BPF context.
 * We undef the extern variable and redefine as a compile-time constant
 * so that any code using jiffies gets a constant 0 instead of a
 * memory load from a kernel variable that does not exist in BPF. */
#ifdef jiffies
#undef jiffies
#endif
#define jiffies ((unsigned long)0)

/* Suppress compiler hint macros that generate extern BTF references.
 * 'unlikely' and 'likely' are normally __builtin_expect wrappers, but
 * some kernel headers define them as macros that call a function when
 * the compiler is in certain modes. Force them to plain expressions.
 * These are re-undef'd here in case the kernel source redefined them. */
#undef unlikely
#undef likely
#define unlikely(x) (x)
#define likely(x)   (x)

/* BPF program entry point - socket filter type (minimal requirements) */
__attribute__((section("socket"), used))
int bpf_prog_min_heap(void *ctx)
{
    /* min_heap: heap ordering invariant after push/pop.
     *
     * Callbacks (__bpf_int_less, __bpf_int_swap) and heap storage
     * (__bpf_heap_storage) are defined at file scope in EXTRA_PRE_INCLUDE.
     *
     * Properties tested:
     *   1. After pushing 3 values, the root (minimum) is <= all pushed values
     *   2. After pop, the new root is >= the popped element
     *   3. Heap size decreases by 1 after pop
     */
    __u32 key0 = 0, key1 = 1, key2 = 2;
    __u64 *v0 = bpf_map_lookup_elem(&input_map, &key0);
    __u64 *v1 = bpf_map_lookup_elem(&input_map, &key1);
    __u64 *v2 = bpf_map_lookup_elem(&input_map, &key2);
    if (!v0 || !v1 || !v2) return 0;
    /* Use small values 1..4 to keep things bounded */
    int vals[3];
    vals[0] = (int)((*v0 & 3) + 1);  /* 1..4 */
    vals[1] = (int)((*v1 & 3) + 1);  /* 1..4 */
    vals[2] = (int)((*v2 & 3) + 1);  /* 1..4 */

    /* Get a pointer to the file-scope heap as min_heap_char */
    min_heap_char *heap = (min_heap_char *)&__bpf_heap_storage;
    __min_heap_init(heap, NULL, 8);

    struct min_heap_callbacks cbs = {
        .less = __bpf_int_less,
        .swp  = __bpf_int_swap,
    };

    /* Push 3 values */
    __min_heap_push(heap, &vals[0], sizeof(int), &cbs, NULL);
    __min_heap_push(heap, &vals[1], sizeof(int), &cbs, NULL);
    __min_heap_push(heap, &vals[2], sizeof(int), &cbs, NULL);

    /* Property 1: root <= all pushed values */
    int *root_ptr = (int *)__min_heap_peek(heap);
    BPF_ASSERT(root_ptr != NULL);
    BPF_ASSERT(*root_ptr <= vals[0]);
    BPF_ASSERT(*root_ptr <= vals[1]);
    BPF_ASSERT(*root_ptr <= vals[2]);

    int root_val = *root_ptr;
    size_t nr_before = heap->nr;

    /* Pop the minimum */
    __min_heap_pop(heap, sizeof(int), &cbs, NULL);

    /* Property 3: size decreased by 1 */
    BPF_ASSERT(heap->nr == nr_before - 1);

    /* Property 2: new root >= popped element */
    if (heap->nr > 0) {
        int *new_root = (int *)__min_heap_peek(heap);
        BPF_ASSERT(new_root != NULL);
        BPF_ASSERT(*new_root >= root_val);
    }
    return root_val;
    return 0;
}

__attribute__((section("license"), used))
char _license[] = "GPL";
