/* BPF verification harness for zstd_fse_decompress
 * Auto-generated by bpf-verify pipeline
 */

/* ---------------------------------------------------------------
 * Step 0: Override autoconf.h CONFIG_* settings that cause BPF
 * compilation failures. kconfig.h (force-included via -include)
 * pulls in generated/autoconf.h which may define these as 1.
 * We undef them here so they take effect before kernel headers.
 * --------------------------------------------------------------- */
/* CONFIG_NUMA pulls in asm/sparsemem.h and NUMA-specific types */
#undef CONFIG_NUMA
/* CONFIG_PARAVIRT pulls in x86 inline asm in paravirt.h */
#undef CONFIG_PARAVIRT
/* CONFIG_MEMCG pulls in this_cpu_read/write (x86 percpu inline asm) in sched/mm.h */
#undef CONFIG_MEMCG

/* ---------------------------------------------------------------
 * Step 1: Suppress kernel export / module metadata macros.
 * These produce non-BPF ELF sections that libbpf cannot handle.
 * --------------------------------------------------------------- */
#define EXPORT_SYMBOL(x)
#define EXPORT_SYMBOL_GPL(x)
#define EXPORT_SYMBOL_NS(x, ns)
#define EXPORT_SYMBOL_NS_GPL(x, ns)
#define MODULE_LICENSE(x)
#define MODULE_AUTHOR(x)
#define MODULE_DESCRIPTION(x)
#define EXPORT_TRACEPOINT_SYMBOL(x)
#define EXPORT_TRACEPOINT_SYMBOL_GPL(x)
#define module_init(x)
#define module_exit(x)

/* ---------------------------------------------------------------
 * Step 1: Suppress WARN_ON / BUG_ON / printk family.
 *
 * These macros call warn_slowpath_fmt, printk, etc. -- functions
 * that are not available in the BPF execution environment and
 * produce unresolved extern symbols that block libbpf loading.
 *
 * For static analysis purposes we want to verify the data-path
 * logic, not the diagnostic/logging paths, so suppressing them
 * is semantically correct for this use case.
 *
 * WARN_ON / WARN must return a scalar (int) because they are
 * commonly used inside if() conditions in kernel code.
 * --------------------------------------------------------------- */
#define WARN_ON(cond)              (0)
#define WARN_ON_ONCE(cond)         (0)
#define WARN(cond, fmt, ...)       (0)
#define WARN_ONCE(cond, fmt, ...)  (0)
#define BUG()                      do {} while (0)
#define BUG_ON(cond)               do { if (cond) {} } while (0)

/* printk / pr_* family -- produce string-literal .rodata relocations */
#define printk(fmt, ...)           do {} while (0)
#define pr_emerg(fmt, ...)         do {} while (0)
#define pr_alert(fmt, ...)         do {} while (0)
#define pr_crit(fmt, ...)          do {} while (0)
#define pr_err(fmt, ...)           do {} while (0)
#define pr_warn(fmt, ...)          do {} while (0)
#define pr_notice(fmt, ...)        do {} while (0)
#define pr_info(fmt, ...)          do {} while (0)
#define pr_debug(fmt, ...)         do {} while (0)
#define pr_devel(fmt, ...)         do {} while (0)
#define pr_cont(fmt, ...)          do {} while (0)

/* ---------------------------------------------------------------
 * Step 1b: Suppress _printk, panic, jiffies.
 *
 * _printk is the actual symbol printk resolves to at link time.
 * panic() calls into the kernel crash path - not available in BPF.
 * jiffies is a per-CPU variable exported from the kernel - not
 * accessible in BPF context without a helper.
 *
 * We define jiffies as a compile-time constant (0) so arithmetic
 * on it is valid; panic as an infinite loop (unreachable in
 * practice); _printk as a no-op.
 * --------------------------------------------------------------- */
/* linux/printk.h, linux/panic.h, and linux/module.h are blocked via
 * -D flags in BPF_CFLAGS so their include guards are pre-defined.
 * We define the symbols those headers would have provided here. */
#define _printk(fmt, ...)          do {} while (0)
#define vprintk(fmt, args)         do {} while (0)
#define printk_deferred(fmt, ...)  do {} while (0)
#define panic(fmt, ...)            do {} while (0)
/* Also stub out common printk-related types/macros that other headers use */
#define printk_ratelimit()         0
#define printk_timed_ratelimit(a,b) 0
/* jiffies: linux/jiffies.h declares it as 'extern unsigned long volatile jiffies'.
 * We cannot block that header (it pulls in linux/types.h etc.).
 * Instead we undef the extern declaration after the include and redefine
 * jiffies as a compile-time constant. This is done in the post-include
 * section below, after all kernel headers have been processed. */

/* BPF_ASSERT: property assertion for verification.
 * If the condition is false the program returns -1 (XDP_ABORTED / TC_ACT_SHOT),
 * which veristat reports as a non-zero return value.
 * Using return -1 instead of a null pointer write avoids the BPF verifier
 * rejecting programs where the false branch is provably unreachable but the
 * verifier still explores it (e.g., pointer equality comparisons). */
#define BPF_ASSERT(cond) do { if (!(cond)) { return -1; } } while(0)

/* BPF map for dynamic (non-constant) inputs.
 * IMPORTANT: This MUST be defined BEFORE the kernel source include.
 * The LLVM BPF backend generates the BTF DATASEC for '.maps' when it
 * first sees the map struct. If kernel headers included later redefine
 * __uint/__type, the DATASEC is already correctly generated.
 *
 * We use the BTF-based map definition syntax that clang understands
 * without needing bpf_helpers.h. The macros below replicate what
 * bpf_helpers.h provides but using only kernel-available types. */
/* Pull in linux/types.h first so __u32/__u64 are available for the
 * map struct definition below. This must come before the source include
 * so the map DATASEC is generated before kernel headers can redefine
 * __uint/__type. */
#include <linux/types.h>

/* Force-undefine __uint and __type before defining the map struct.
 * Kernel headers may define these differently; we need our exact form
 * for the LLVM BPF backend to generate a DATASEC entry in BTF. */
#undef __uint
#undef __type
#define __uint(name, val) int (*name)[val]
#define __type(name, val) typeof(val) *name
struct {
    __uint(type, 1 /* BPF_MAP_TYPE_ARRAY */);
    __uint(max_entries, 4);
    __type(key, __u32);
    __type(value, __u64);
} input_map __attribute__((section(".maps"), used));

/* bpf_map_lookup_elem helper declaration */
static void *(*bpf_map_lookup_elem)(void *map, const void *key) =
    (void *) 1 /* BPF_FUNC_map_lookup_elem */;

/* Extra dependencies (other translation units this file calls into) */

/* Per-file pre-include code: macros/stubs injected BEFORE the source file
 * (e.g. identity macros to suppress 6-arg non-static functions). */
/* Forward declarations with internal_linkage for all >5-arg non-static
 * functions in fse_decompress.c. Use unsigned int for FSE_DTable (it's a
 * typedef for unsigned int in fse.h). Block fse.h to prevent conflict. */
typedef unsigned int FSE_DTable;
__attribute__((internal_linkage))
size_t FSE_buildDTable_wksp(FSE_DTable *dt, const short *normalizedCounter,
    unsigned maxSymbolValue, unsigned tableLog,
    void *workspace, size_t workspaceSize);
__attribute__((internal_linkage))
size_t FSE_decompress_wksp(void *dst, size_t dstCapacity,
    const void *cSrc, size_t cSrcSize,
    unsigned maxLog, void *workSpace, size_t wkspSize);
__attribute__((internal_linkage))
size_t FSE_decompress_wksp_bmi2(void *dst, size_t dstCapacity,
    const void *cSrc, size_t cSrcSize,
    unsigned maxLog, void *workSpace, size_t wkspSize, int bmi2);
/* Override __GNUC__ to force software fallbacks for __builtin_clz
 * (opcode 192, not supported by BPF backend). bitstream.h uses it. */
#define __GNUC__ 2
/* Block fse.h (both sections) to prevent conflicts. */
#define FSE_H
#define FSE_H_FSE_STATIC_LINKING_ONLY
/* FSE_CTable is defined in the first section of fse.h (which we blocked). */
typedef unsigned int FSE_CTable;
/* fse_decompress.c is a template file that requires these macros.
 * They are normally defined at the bottom of fse.h (which we blocked). */
typedef unsigned char BYTE;
typedef struct { unsigned short newState; unsigned char symbol; unsigned char nbBits; } FSE_decode_t;
#define FSE_FUNCTION_TYPE BYTE
#define FSE_FUNCTION_EXTENSION
#define FSE_DECODE_TYPE FSE_decode_t
/* These constants are defined in the blocked fse.h static-linking-only section.
 * fse_decompress.c uses them directly. */
#define FSE_MAX_MEMORY_USAGE 14
#define FSE_MAX_TABLELOG  (FSE_MAX_MEMORY_USAGE-2)
#define FSE_TABLELOG_ABSOLUTE_MAX 15
#define FSE_MAX_SYMBOL_VALUE 255
/* FSE_DTABLE_SIZE_U32 is defined in the blocked fse.h (public section). */
#define FSE_DTABLE_SIZE_U32(maxTableLog) (1 + (1<<(maxTableLog)))
typedef struct { unsigned short tableLog; unsigned short fastMode; } FSE_DTableHeader;
typedef struct { size_t state; const void *table; } FSE_DState_t;
/* Include bitstream.h to get BIT_DStream_t and the BIT_* inline functions.
 * bitstream.h is normally included by fse.h's static section (which we blocked).
 * With __GNUC__ 2, bitstream.h uses the software fallback for BIT_highbit32
 * instead of __builtin_clz (opcode 192, not supported by BPF). */
#include "/home/ubuntu/bpf-next-0aa637869/lib/zstd/common/bitstream.h"
/* FSE_initDState/decodeSymbol/decodeSymbolFast are static inline in fse.h's
 * static-linking-only section (which we blocked). Provide stubs so the
 * BPF object has no unresolved extern references. */
static __always_inline void FSE_initDState(FSE_DState_t *s, BIT_DStream_t *b,
    const FSE_DTable *dt)
{ (void)s; (void)b; (void)dt; }
static __always_inline unsigned char FSE_decodeSymbol(FSE_DState_t *s,
    BIT_DStream_t *b)
{ (void)s; (void)b; return 0; }
static __always_inline unsigned char FSE_decodeSymbolFast(FSE_DState_t *s,
    BIT_DStream_t *b)
{ (void)s; (void)b; return 0; }
static __always_inline unsigned FSE_endOfDState(const FSE_DState_t *s)
{ (void)s; return 1; }

/* Include the kernel source file */
#include "/home/ubuntu/bpf-next-0aa637869/lib/zstd/common/fse_decompress.c"

/* Per-file extra preamble: stubs injected AFTER the source file include
 * (so they can reference types defined in the source). */


/* Post-include fixups: redefine symbols that were declared as externs
 * in kernel headers but must be constants in the BPF context.
 * We undef the extern variable and redefine as a compile-time constant
 * so that any code using jiffies gets a constant 0 instead of a
 * memory load from a kernel variable that does not exist in BPF. */
#ifdef jiffies
#undef jiffies
#endif
#define jiffies ((unsigned long)0)

/* Suppress compiler hint macros that generate extern BTF references.
 * 'unlikely' and 'likely' are normally __builtin_expect wrappers, but
 * some kernel headers define them as macros that call a function when
 * the compiler is in certain modes. Force them to plain expressions.
 * These are re-undef'd here in case the kernel source redefined them. */
#undef unlikely
#undef likely
#define unlikely(x) (x)
#define likely(x)   (x)

/* BPF program entry point - socket filter type (minimal requirements) */
__attribute__((section("socket"), used))
int bpf_prog_zstd_fse_decompress(void *ctx)
{
    return 0;
    return 0;
}

__attribute__((section("license"), used))
char _license[] = "GPL";
